const TicketType = {
  TECH: "TECH",
  PRODUCT_INQUIRY: "PRODUCT_INQUIRY",
  PAYMENTS_AND_BILLING: "PAYMENTS_AND_BILLING",
  COMPLAINTS_AND_FEEDBACK: "COMPLAINTS_AND_FEEDBACK",
};

export default TicketType;
